# Generated by Django 3.2.8 on 2023-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0004_alter_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='emp_id',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(choices=[('COS', 'CORE SUBJECT'), ('OPS', 'OPTIONAL SUBJECT')], max_length=4),
        ),
    ]
