# Generated by Django 4.2 on 2023-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0007_alter_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default='approval pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
