# Generated by Django 4.2.1 on 2023-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0009_feedback_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
