# Generated by Django 4.2.1 on 2023-05-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0011_attendance_mark_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(choices=[('COA', 'Computer Architecture and Analysis'), ('AOP', 'Art of Programming'), ('RM', 'Research Methodology'), ('BA', 'Business administration'), ('HM', 'Hotel Management'), ('MH', 'Management Hotel'), ('AC', 'Accounting'), ('CO', 'Commerce')], max_length=4),
        ),
    ]
